databases:
  - name: ola
    plan: free
    databaseName: ola_4hcn
    user: user

services:
  - type: web
    plan: free
    name: audition
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn audition.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ola
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4